### ISSUE TITLE
Trouble Compiling on MacOS Sierra

### ISSUE THREAD

**Issue by msalman86** [dcevm/dcevm#111]
Hey,

I am unable to compile/build dcevm on MacOS Sierra 10.12.1 for  java version jdk8u112-b16. Please see attached debug log. I would appreciate any help, thank you.
[build-error.log.zip](https://github.com/dcevm/dcevm/files/574089/build-error.log.zip)

**Comment by skybber** [comment]
Most likely this is not dcevm problem since it doesn't change openjdk build process. You should look for HOWTO build openjdk on Mac

**Comment by saqibahmed515** [comment]
From the log file you provided, initial errors are inside GCC library. Try using some other version of GCC. As far as I could gather, you brewed 4.8 GCC for this build specially since current GCC version is 6.x. I built JDK with and without DCEVM patches in linux and one outta 3 times errors were either GCC related or makefile related. So it shouldn't be a DCEVM patch problem.
Try using 

```
./configure --with-debug-level=slowdebug --with-target-bits=64 --disable-zip-debug-info 
make all
```

for a change. :-)

**Comment by oranheim** [comment]
I experoence same problem on MacOS Sierra and I've tried to compile with gcc-49, gcc-5, gcc-6 without  success.

I am using Zulu JDK:
```
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (Zulu 8.19.0.1-macosx) (build 1.8.0_112-b16)
OpenJDK 64-Bit Server VM (Zulu 8.19.0.1-macosx) (build 25.112-b16, mixed mode)
```

In the gradle build system, where can I modify the `configure` statement?

**Comment by skybber** [comment]
OpenJDK / gcc setup problem.
