### ISSUE TITLE
Java 9 integration

### ISSUE THREAD

**Issue by lukyer** [dcevm/dcevm#134]
Hi,
are there any plans for supporting java9 jdk integration? 

Thanks.

**Comment by idubrov** [comment]
No. There are no plans to support jdk9.

**Comment by skybber** [comment]
We are working on jdk9 support, there will be support for jdk9 certainly.

**Comment by lukyer** [comment]
So what? :D

**Comment by skybber** [comment]
Since build system for dcevm7 and dcevm8 is not able to use for java9, we have to extend dcevm from standard OpnJDK and we created a new repository for the project. Jdk-hotswap9 (dcevm9) beta version is just available at [HotswapProject](https://github.com/HotswapProjects/openjdk-jdk9/releases/tag/jdk9-b94-dcevm-beta). It is bundled with HotswapAgent by default.

**Comment by skybber** [comment]
There is  https://github.com/TravaOpenJDK/trava-jdk-11-dcevm for j11 now
