### ISSUE TITLE
how to install dcevm by DCEVM-8u152-installer.jar without having admin privilege on window

### ISSUE THREAD

**Issue by Dhirajpandit** [dcevm/dcevm#147]

**Comment by przemelek** [comment]
I would try to copy existing JVM to some other folders than Program Files or similar (not sure where it is on Windows now, it used to live in Program Files), for example create C:\JDKs\ and copy your installation of JVM to folder C:\JDKs\JDK8u152.
Next, run installer (as normal user) and point this new folder.

Latter you should be able to configure IDE to run programs you are working on with this special JVM.

In general DCEVM installer needs your case admin privileges not because of some problems, but because by default from Windows 7 (or even Vista?)) normal users are not allowed to fiddle with files in Program Files or Program Files (x86). So to avoid this problem it may make sense to create special JDK location for JDK which you want to modify.
