### ISSUE TITLE
Please, keep the release of the binarys always following the latest released patch

### ISSUE THREAD

**Issue by andreasboos** [dcevm/dcevm#60]
Build OpenJDK is not a simple process for windows users. I gave up trying.

**Comment by schweighart** [comment]
Building is really easy if you find the right manual :-) But till then you are totally lost.

Use this instructions for the basic setup:
https://weblogs.java.net/blog/simonis/archive/2011/10/28/yaojowbi-yet-another-openjdk-windows-build-instruction
Yes I also used Windows XP x64. You need to install Service Pack 2 upfront. But do NOT install any other security updates. Especially not .net Framework 4.5. 
Some of the links in this manual do not work anymore, but it is easy to google everything.
VisualC++ 2010 Express needs to be without service pack.
Ant can be in a newer version (I used 1.9.4)
Follow the instructions including cygwin. You can skip the rest.
You have to enable mq extention in Mercurial.
You have to remove/rename link.exe from cygwin/lib folder.
If you install cygwin to its default folder (c:\cygwin64) you have to change it in build.cmd also because this wants cygwin in c:\cygwin.

**Comment by thodt-md** [comment]
Tried the recipe on Windows 7 x64, and failed to install WIC (not needed?). After getting the build to start, it failed in the end with some cryptic link.exe error. Windows update mentioned [here](https://github.com/dcevm/dcevm/issues/11#issuecomment-41505987) helped.

**Comment by f1ztech** [comment]
Hi @thodt-md, have you succeeded in compiling latest version for windows? If yes, can you please give a link to it or send by email.
Thanks!

**Comment by thodt-md** [comment]
Yes, but only the [x64 version](https://drive.google.com/file/d/0B7jajEuoWruHRk0tYnpRa0ZRNlE/view?usp=sharing) for a fellow colleague. Haven't tried it myself though (I use Linux), but the tests passed successfully.

**Comment by idubrov** [comment]
Try latest release I published (Java 8u45).

**Comment by f1ztech** [comment]
Great! Thanks a lot
