### ISSUE TITLE
JBoss won't run on a DCEVM patched JDK/JRE with GC's other than Serial

### ISSUE THREAD

**Issue by mystarrocks** [dcevm/dcevm#64]
After patching one of my `jdk 1.6.0.35 (64 Bit)` with the `DCEVM` (I used the Replace by DCEVM option), my `JBoss EAP 6.2` won't run on this VM anymore since the VM startup options include:

`-XX:+UseParNewGC -XX:+UseConcMarkSweepGC`

failing with the below error:

`Must use the serial GC in the Dynamic Code Evolution VM`
`Could not create the Java virtual machine.`

Although it's only my local machine where I can switch to use the `Serial GC`, I would like to see if a fix can be made to allow it to work with other `GC` strategies.

**Comment by idubrov** [comment]
No, it's somewhat unrealistic. DCEVM uses patched GC to do object transformations while redefining classes. I would expect patching other GC would be much harder than serial one, if possible at all, simply because serial GC is really trivial and does not have constraints other GC might have.

So closing at this point.
